### ISSUE TITLE
QuestCraft Version 3 Microsoft Login not responding

### ISSUE THREAD

**Issue by emanuelkoseos** [QuestCraftPlusPlus/QuestCraft#417]
Hi,

Newly installed QuestCraft QCXR-3.0.0.apk on Meta Quest 2 VR; I managed to authorize the device via browser.

When I now open QuestCraft it says you can login now, press the Microsoft Login button; there is also a debug button below it.

Neither of these buttons are responding - not indication that they work.

I also tried QCXR - 2.0.1 patch version and can't log in at all = get the 401 unauthorized error; when I check my account I see that it did in fact allow me to log in; but application is not detecting that I logged in

**Comment by Cartrigger** [comment]
Hi, a 401 error either means that your account is under 18, doesn't own Java edition, or doesn't have a setup Java edition profile, the new launcher may not show an error, but it's probably erroring when it tries to create a profile.

**Comment by emanuelkoseos** [comment]
Yes this is a bug - I do own the java edition, I am not under 18, and do have a java edition profile on Minecraft.

I can play bedrock and java edition on my PC without any issues; I can log in without any issues. Not the 401 comment was for version 2.0 ; I am currently running version 3.0 with vivecraft which freezes

**Comment by emanuelkoseos** [comment]
I've been told the alternative way is to install vivecraft instead and use wireless with the PC that remap the display; will try this next if questcraft won't run.

**Comment by rasta420421** [comment]
I am having the same issues to a T, I have not tried the 2.0 patch though

**Comment by CADIndie** [comment]
This issue was resolved in [Release 3.0.1](https://github.com/QuestCraftPlusPlus/QuestCraft/releases/tag/3.0.1) and should require no further support.

**Comment by rasta420421** [comment]
I have version 3.0.1
The problems listed are still happening for me.
1. Open questcraft
2. Click microsoft login
3. Go to microsft.com/link and enter code
4. Click microsoft login on questcraft  
5. Cursor freezes
6. Resumes main screen

**Comment by BeckPhillips** [comment]
I am having the exact same issue as rasta420421
